### ISSUE TITLE
鼠标悬浮节点的锚点是怎么显示的呢 

### ISSUE THREAD

**Issue by mmzsyh** [tuchongyang/flowchart-editor#10]
您好 最近公司项目要画一个可配置的可视化图  参考了您的代码 发现 不太清楚鼠标悬浮到节点 节点上的4个锚点是怎么出现的 没看到您的激活配置在哪  可否指点一下 万分感谢

**Comment by tuchongyang** [comment]
具体代码在 src/components/FlowchartEditor/global/g6/utils/anchor/draw.js   69 ~ 78行

**Comment by tuchongyang** [comment]
@mmzsyh   g6/node/base.js   71行，此处调用 `utils.anchor.draw(cfg, group)`

**Comment by mmzsyh** [comment]
好的&nbsp; 感谢告知~&nbsp; 谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tuchongyang/flowchart-editor"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月4日(星期三) 下午4:11
收件人:&nbsp;"tuchongyang/flowchart-editor"<flowchart-editor@noreply.github.com&gt;;
抄送:&nbsp;"张鸣"<815989056@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [tuchongyang/flowchart-editor] 鼠标悬浮节点的锚点是怎么显示的呢  (#10)





 
@mmzsyh   g6/node/base.js   71行，此处调用 utils.anchor.draw(cfg, group)
